### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by psiinon** [interference-security/DVWS#1]
This project looks great :)
Any chance of creating a docker image for it? That would make it much easier to install.
I've started a collection of vuln apps: https://hub.docker.com/u/owaspvwad/ so v happy to add it there.

**Comment by interference-security** [comment]
[schniggie](https://twitter.com/schniggie) has created a docker image which is available here [https://hub.docker.com/r/tssoffsec/dvws/](https://hub.docker.com/r/tssoffsec/dvws/).
