### ISSUE TITLE
DB dependent excercises don't work

### ISSUE THREAD

**Issue by davevs** [interference-security/DVWS#2]
I tried to install DVWS and everything seems to working, but the DB depending exercises don't work.

What I have tried so far:
- create DB both as root and dedicated user
- verified existence DB with mysqlshow
- created tables via setup in DVWS; appears to be working

However, when I e.g. try stored XSS the Firefox console tells me the server closes the connection because the path can't be found.

Exercises not depending on DB work fine (e.g. command injection and reflected XSS).

Any ideas?

**Comment by interference-security** [comment]
It would be helpful if you can share a screenshot of the Firefox console and terminal from where you executed `php ws-socket.php` when you try to perform a DB depended exercise such as Stored XSS.

**Comment by davevs** [comment]
hmmm. not sure what happened, but I rebuild the Docker container I installed DVWS in and now it just works .... issue can be closed
