### ISSUE TITLE
ping me in command execution page is not working

### ISSUE THREAD

**Issue by KajanM** [interference-security/DVWS#4]
`environment => Windows 10, XAMPP (PHP 7)`

initially
![access denied](https://user-images.githubusercontent.com/17596394/37556168-0998a910-2a18-11e8-958e-ee79210a278d.PNG)

after starting `ws-socket.php` with administrator privilege
![bad-value](https://user-images.githubusercontent.com/17596394/37556186-619792b6-2a18-11e8-985c-a4b0ea28ee6e.PNG)

After changing line 24 of [`CommandExecution.php`](https://github.com/interference-security/DVWS/blob/master/class/CommandExecution.php) to `$reply_data = shell_exec('ping '.$msg);`

everything is working fine.
![ping-working](https://user-images.githubusercontent.com/17596394/37556231-fb81f2cc-2a18-11e8-9c92-a248927e9a09.PNG)

command injection is also working fine
![success](https://user-images.githubusercontent.com/17596394/37556233-febbad2a-2a18-11e8-86d1-55c774635ab7.PNG)

**Comment by KajanM** [comment]
also, it must be noted that when running [docker](https://hub.docker.com/r/tssoffsec/dvws/) image in kali linux no such problem is observed. Is it because of PHP version mismatch in XAMPP?

**Comment by kingthorin** [comment]
`-c` is the Linux (*nix) count switch. The Windows equivalent is `-n`, number of echo requests to send.

When ping is run under Linux without specifying count then it just keeps running until cancelled.

**Comment by KajanM** [comment]
ohh, thank you @kingthorin. So DVWS is built mainly for Linux environment right?

**Comment by kingthorin** [comment]
That _seems_ to be an assumption that was made. 

There must be a way to check platform in php and then use the appropriate switch...I would hope.

Edit:  http://php.net/manual/en/function.php-uname.php

**Comment by interference-security** [comment]
Platform check has been implemented for ping command (https://github.com/interference-security/DVWS/commit/01d36bd36076929d008c223f8b5d92ec8ba86af0). Thanks @KajanM and @kingthorin
