### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by UtkarshKher** [interference-security/DVWS#6]
![1](https://user-images.githubusercontent.com/38111424/38381121-57e21412-38f5-11e8-812b-273e8b8d6061.png)
![2](https://user-images.githubusercontent.com/38111424/38381126-5b11065c-38f5-11e8-8636-2fa985387515.png)
![3](https://user-images.githubusercontent.com/38111424/38381135-5e73322a-38f5-11e8-967a-038921f83713.png)

**Comment by interference-security** [comment]
It seems your host on which Firefox is running is unable to connect to `dvws.local` hostname. Make sure that your Ubuntu host can resolve `dvws.local` hostname. Run the following command from your Ubuntu host to ensure hostname to IP address resolution is working:
`nslookup dvws.local`

When the connection to Web Socket service is successful, you will see a log entry in Console inside Developer Tools. Also, you can check the terminal from where you started the Web Socket service to ensure incoming requests are accepted and connections are established successfully.
