### ISSUE TITLE
Sending and receiving heartbeat messages

### ISSUE THREAD

**Issue by eakirtas** [interference-security/DVWS#7]
Many Websocket applications implements heartbeat messages, called PING/PONG, to keep websocket connection alive. 

It will be great if DVWS has an option to add heartbeat messages. That will help testing manual established websocket connections from proxies like ZAP. In order to achieve that, we could use some parameters at ws-socket.php. An example: 

```
ws-socket.php --heartbeat--intervel <ms> --heartbeat-time <ms> 
```
I have being trying to implement that but i am not so familiar with javascript/php. 

Thank you :)

**Comment by interference-security** [comment]
Interesting point. I am glad to know that you want to contribute to this project. If you already have a sample code please share a link to it. I will also try to make it work ASAP.

**Comment by rbgCODE** [comment]
Was there ever example source provided or are there any plans to implement this change?  I do think it would be helpful.

**Comment by interference-security** [comment]
Example code was shared/posted. I agree this is a very helpful change but time and sample code will help implement it faster. I am open to receiving PR for this change and merge it upon review. Sadly, I have not been able to get this done till now. But will look into it now. If you have sample code, please do share.

**Comment by interference-security** [comment]
It seems the change required is to add the below mentioned code after `line 95` of `ws-socket.php`
`$router->enableKeepAlive($server->loop, 30);`
where, `30` will be accepted from user as a command-line parameter.

I will test this change and if found working will merge it with master.

Source: http://socketo.me/docs/migration-3#keepalive

**Comment by rbgCODE** [comment]
Yes, it should be that simple and the syntax woks where the time between would just be a variable but if for some reason it doesn't work like that, just let me know.  I have some time and I could get a working script for you then email it over so you can integrate it.

**Comment by interference-security** [comment]
`$router->enableKeepAlive($server->loop, 30);` does not work and gives PHP fatal error `Call to undefined method Ratchet\Http\Router::enableKeepAlive()`.
This is because `enableKeepAlive` has to be called on `WsServer` and not `Router`. I could not get it done due to my limited knowledge of Ratchet and its RouteCollection. See if you know how to add `enableKeepAlive` in ws-socket.php. I will keep digging more for now.

Also, composer and react+mysql needs to be upgraded for `enableKeepAlive` to work. So `composer.json` should look like this now:
```
{
    "require": {
        "cboden/ratchet": "*",
        "react/mysql": "*"
    }
}
```

After that from the location of `composer.json` run the following command to install it: `composer install`

**Comment by rbgCODE** [comment]
I have a lot of work to do tomorrow but Wed I have some extra time, I will see if with the changes you made to .json I can get a functional script working to send over.

**Comment by interference-security** [comment]
Sure. I have created a [dev branch](https://github.com/interference-security/DVWS/tree/dev) with the updated `composer.json`. Have to clone the dev branch and run the following command to get the latest version of dependencies installed in DVWS: `composer install`

**Comment by interference-security** [comment]
Heartbeat has been implemented. Refer commit: https://github.com/interference-security/DVWS/commit/6eb1227b19ce6faa3c2f96baf4b5be080cf8140a
